version: '3.8'

services:
  database:
    image: postgres:14-alpine
    container_name: hedgedoc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hedgedoc
      POSTGRES_USER: hedgedoc
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:latest
    container_name: hedgedoc_app
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "3001:3000"
    environment:
      CMD_DOMAIN: "192.168.0.102:3001"
      CMD_URL_ADDPORT: "false"
      CMD_PROTOCOL_USESSL: "false"
      CMD_DB_URL: postgres://hedgedoc:supersecret@database:5432/hedgedoc
      CMD_ALLOW_ANONYMOUS: "true"
      CMD_ALLOW_ANONYMOUS_EDITS: "true"
      CMD_SESSION_SECRET: "a_super_secret_session_key"
      CMD_CSP_ENABLE: "false"

volumes:
  postgres_data:
